# Generated by go2rpm 1.6.0
%bcond_without check

# https://github.com/projectdiscovery/dnsx
%global goipath         github.com/projectdiscovery/dnsx
Version:                1.0.9

%gometa

%global goname          dnsx

%global common_description %{expand:
Dnsx is a fast and multi-purpose DNS toolkit allow to run multiple DNS queries
of your choice with a list of user-supplied resolvers.}

%global golicenses      LICENSE.md
%global godocs          SECURITY.md README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Dnsx is a fast and multi-purpose DNS toolkit allow to run multiple DNS queries of your choice with a list of user-supplied resolvers

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE.md
%doc SECURITY.md README.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
