# Generated by go2rpm 1.8.2
%bcond_without check
%global debug_package %{nil}

# https://github.com/ysmood/goob
%global goipath         github.com/ysmood/goob
Version:                0.4.0

%gometa -f

%global common_description %{expand:
A lightweight buffered event lib.}

%global golicenses      LICENSE
%global godocs          readme.md

Name:           %{goname}
Release:        %autorelease
Summary:        A lightweight buffered event lib

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
