# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/projectdiscovery/hmap
%global goipath         github.com/projectdiscovery/hmap
Version:                0.0.1

%gometa

%global common_description %{expand:
Hybrid memory/disk map}

%global golicenses      LICENSE
%global godocs          README.md example

Name:           %{goname}
Release:        1%{?dist}
Summary:        Hybrid memory/disk map

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/syndtr/goleveldb/leveldb)
BuildRequires:  golang(github.com/syndtr/goleveldb/leveldb/iterator)
BuildRequires:  golang(github.com/syndtr/goleveldb/leveldb/util)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Mon Aug 30 2021 Mikel Olasagasti Uranga <mikel@olasagasti.info> - 0.0.1-1
- Initial package

