# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/projectdiscovery/dnsx
%global goipath         github.com/projectdiscovery/dnsx
Version:                1.0.6

%gometa

%global common_description %{expand:
Dnsx is a fast and multi-purpose DNS toolkit allow to run multiple DNS queries
of your choice with a list of user-supplied resolvers.}

%global golicenses      LICENSE.md
%global godocs          SECURITY.md README.md

Name:           dnsx
Release:        1%{?dist}
Summary:        A fast and multi-purpose DNS toolkit to run multiple DNS queries

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/miekg/dns)
BuildRequires:  golang(github.com/projectdiscovery/clistats)
BuildRequires:  golang(github.com/projectdiscovery/fileutil)
BuildRequires:  golang(github.com/projectdiscovery/goconfig)
BuildRequires:  golang(github.com/projectdiscovery/gologger)
BuildRequires:  golang(github.com/projectdiscovery/gologger/levels)
BuildRequires:  golang(github.com/projectdiscovery/hmap/store/hybrid)
BuildRequires:  golang(github.com/projectdiscovery/iputil)
BuildRequires:  golang(github.com/projectdiscovery/mapcidr)
BuildRequires:  golang(github.com/projectdiscovery/retryabledns)
BuildRequires:  golang(github.com/rs/xid)
BuildRequires:  golang(go.uber.org/ratelimit)

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE.md
%doc SECURITY.md README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Mon Aug 30 2021 Mikel Olasagasti Uranga <mikel@olasagasti.info> - 1.0.6-1
- Initial package

