# Generated by go2rpm 1.6.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/projectdiscovery/fileutil
%global goipath         github.com/projectdiscovery/fileutil
%global commit          d67292d8b36f1e1b3e30f22df1e1af295e6adaa4

%gometa

%global common_description %{expand:
Various helpers to interact with files.}

%global golicenses      LICENSE.md
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        %autorelease -p
Summary:        Various helpers to interact with files

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
ln -s %{_builddir}/fileutil-%{commit} %{_builddir}/fileutil
# TestDownloadFile requires network
for test in "TestDownloadFile" \
; do
awk -i inplace '/^func.*'"$test"'\(/ { print; print "\tt.Skip(\"disabled failing test\")"; next}1' $(grep -rl $test)
done
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
