# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/projectdiscovery/blackrock
%global goipath         github.com/projectdiscovery/blackrock
%global commit          b38689ae3a2e401eca39729ea3101a42bfe334b3

%gometa

%global common_description %{expand:
Blackrock cipher based on masscan.}

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Blackrock cipher based on masscan

License:        # FIXME

URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Mon Aug 30 2021 Mikel Olasagasti Uranga <mikel@olasagasti.info> - 0-0.1%{?dist}.20210830gitb38689a
- Initial package

