# Generated by go2rpm 1.8.2
%bcond_without check
%global debug_package %{nil}

# https://github.com/akrylysov/pogreb
%global goipath         github.com/akrylysov/pogreb
Version:                0.10.1

%gometa -f

%global common_description %{expand:
Embedded key-value store for read-heavy workloads written in Go.}

%global golicenses      LICENSE
%global godocs          docs CHANGELOG.md README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Embedded key-value store for read-heavy workloads written in Go

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
