# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/projectdiscovery/fileutil
%global goipath         github.com/projectdiscovery/fileutil
%global commit          ebba15fa53ca8a29cf7633e3c78be4fb5c21a2a5

%gometa

%global common_description %{expand:
# FIXME}

%global golicenses      LICENSE.md
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        None

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/karrick/godirwalk)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/require)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

#%%if %{with check}
#%%check
#%%gocheck
#%%endif

%gopkgfiles

%changelog
* Mon Aug 30 2021 Mikel Olasagasti Uranga <mikel@olasagasti.info> - 0-0.1%{?dist}.20210830gitebba15f
- Initial package

