# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/projectdiscovery/retryabledns
%global goipath         github.com/projectdiscovery/retryabledns
Version:                1.0.12

%gometa

%global common_description %{expand:
Retryable DNS client in Go.}

%global golicenses      LICENSE.md
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Retryable DNS client in Go

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/miekg/dns)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/require)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%gopkgfiles

%changelog
* Mon Aug 30 2021 Mikel Olasagasti Uranga <mikel@olasagasti.info> - 1.0.12-1%{?dist}
- Initial package

