# Generated by go2rpm 1.8.2
%bcond_without check
%global debug_package %{nil}

# https://github.com/ulule/deepcopier
%global goipath         github.com/ulule/deepcopier
%global commit          45decc6639b634774af79cefff24e6b9670f5847

%gometa -f

%global common_description %{expand:
Simple struct copying for golang.}

%global golicenses      LICENSE
%global godocs          examples README.md

Name:           %{goname}
Version:        0
Release:        %autorelease -p
Summary:        Simple struct copying for golang

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
