# Generated by go2rpm 1.8.2
%bcond_without check
%global debug_package %{nil}

# https://github.com/dgraph-io/ristretto
%global goipath         github.com/dgraph-io/ristretto
Version:                0.1.1

%gometa -f

%global common_description %{expand:
A high performance memory-bound Go cache.}

%global golicenses      LICENSE z/LICENSE
%global godocs          CHANGELOG.md README.md z/README.md

Name:           %{goname}
Release:        %autorelease
Summary:        A high performance memory-bound Go cache

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
