# Generated by go2rpm 1.8.2
%bcond_without check
%global debug_package %{nil}

# https://github.com/projectdiscovery/networkpolicy
%global goipath         github.com/projectdiscovery/networkpolicy
Version:                0.0.1
%global commit          22b13ce54fff23e8dde6fc703bbaf6b4304c1e69

%gometa -f

%global common_description %{expand:
Network Policy Helper.}

%global golicenses      LICENSE.md
%global godocs          README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Network Policy Helper

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
