# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/projectdiscovery/reflectutil
%global goipath         github.com/projectdiscovery/reflectutil
%global commit          4d90952bf92fadb5bf477090b0aea40536120bf0

%gometa

%global common_description %{expand:
Library containing reflection helpers.}

%global golicenses      LICENSE.md
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Library containing reflection helpers

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/require)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Mon Aug 30 2021 Mikel Olasagasti Uranga <mikel@olasagasti.info> - 0-0.1.20210830git4d90952
- Initial package

