# Generated by go2rpm 1.8.2
%bcond_without check
%global debug_package %{nil}

# https://github.com/go-rod/rod
%global goipath         github.com/go-rod/rod
Version:                0.112.0

%gometa -f

%global common_description %{expand:
A Devtools driver for web automation and scraping.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        %autorelease
Summary:        A Devtools driver for web automation and scraping

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

BuildRequires:  chromium

%description %{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
