# Generated by go2rpm 1.8.2
%bcond_without check
%global debug_package %{nil}

# https://github.com/dgryski/go-farm
%global goipath         github.com/dgryski/go-farm
%global commit          a6ae2369ad13dc757768086f0cb902728c7e03e5

%gometa -f

%global common_description %{expand:
Go-farm: a pure-Go farmhash implementation.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        %autorelease -p
Summary:        Go-farm: a pure-Go farmhash implementation

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
