# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/projectdiscovery/clistats
%global goipath         github.com/projectdiscovery/clistats
Version:                0.0.8

%gometa

%global common_description %{expand:
A command based package for simple display of statistics.}

%global golicenses      LICENSE
%global godocs          examples README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        A command based package for simple display of statistics

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(go.uber.org/atomic)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Mon Aug 30 2021 Mikel Olasagasti Uranga <mikel@olasagasti.info> - 0.0.8-1
- Initial package

