# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/projectdiscovery/goconfig
%global goipath         github.com/projectdiscovery/goconfig
%global commit          f893ccd0c69c2461e0778adf72fb583efe8e28ee

%gometa

%global common_description %{expand:
Helper library to save/restore internal values across multiple runs.}

%global golicenses      LICENSE.md
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Helper library to save/restore internal values across multiple runs

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/projectdiscovery/reflectutil)
BuildRequires:  golang(gopkg.in/ini.v1)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/require)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Mon Aug 30 2021 Mikel Olasagasti Uranga <mikel@olasagasti.info> - 0-0.1%{?dist}.20210830gitf893ccd
- Initial package

