# Generated by go2rpm 1.8.2
%bcond_without check
%global debug_package %{nil}

# https://github.com/dgraph-io/badger
%global goipath         github.com/dgraph-io/badger
Version:                3.2103.4

%gometa -f

%global common_description %{expand:
Fast key-value DB in Go.}

%global golicenses      LICENSE
%global godocs          docs CODE_OF_CONDUCT.md CONTRIBUTING.md CHANGELOG.md\\\
                        VERSIONING.md README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Fast key-value DB in Go

License:        MIT AND Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
