# Generated by go2rpm 1.6.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/projectdiscovery/retryabledns
%global goipath         github.com/projectdiscovery/retryabledns
Version:                1.0.15

%gometa

%global common_description %{expand:
Retryable DNS client in Go.}

%global golicenses      LICENSE.md
%global godocs          README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Retryable DNS client in Go

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
for test in "TestConsistentResolve" "TestUDP" "TestTCP" "TestDOH" "TestDOT" "TestQueryMultiple" "TestResolvers" \
; do
awk -i inplace '/^func.*'"$test"'\(/ { print; print "\tt.Skip(\"disabled failing test\")"; next}1' $(grep -rl $test)
done
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
