# Generated by go2rpm 1.8.2
%bcond_without check
%global debug_package %{nil}

# https://github.com/ysmood/leakless
%global goipath         github.com/ysmood/leakless
Version:                0.8.0

%gometa -f

%global common_description %{expand:
Thou shalt not stay.}

%global golicenses      LICENSE
%global godocs          readme.md

Name:           %{goname}
Release:        %autorelease
Summary:        Thou shalt not stay

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
